### PR TITLE
Bookstore: Use Redux in React components

### PR DESCRIPTION
**Pull request by kinginthenorthcodez**
## Bookstore: Use Redux in React components 👍🏽 
- Use store, actions and reducers in React.
- Connect React and Redux.
### Additional requirements 👍🏽 
- Implement a filtering feature with a hardcoded list of categories

Warm Regards
@kinginthenorthcodez

### CODE REVIEW

**Review by bimbolabuari — CHANGES_REQUESTED** [review]
Hi @kinginthenorthcodez, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- State is immutable
- Correct Gitflow

## Required Changes 
- The main React component (app) should be wrapped in Provider and assign store
```
import store from './redux/configureStore';

    ReactDOM.render(
    <Provider store={store}>
        <App />
    </Provider>,
    document.getElementById('root')
    )


```

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kinginthenorthcodez** [comment]
@bimbolabuari  Thanks for that kind suggestion. My entire application is wrapped in the <Layout/> component and not <App/> which is also okay I believe.  It looks like so ⬇️ 
https://github.com/kinginthenorthcodez/bookstore/blob/f11e1bbf8607a1a507369d5718b062f615b1e145/src/index.js#L1-L20

**Review by sja-thedude — APPROVED** [review]
## Project Approved 👍 

Hi @kinginthenorthcodez, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

giphy

Cheers and Happy coding!👏👏👏

## Optional: As the previous reviewer forgot this point that's why it's optional. Kindly update your readme file with the correct header and description for of the next milestone.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kinginthenorthcodez** [comment]
@sja-thedude thanks for the heads-up 👍🏽

**Comment by kinginthenorthcodez** [comment]
Merged #3  into developemnt

**Pull request merged**
